### ISSUE TITLE
Script error: FileNotFoundError: [Errno 2] No such file or directory: '{install_directory}\\../../python/renewSSLScript/settings.json'

### ISSUE THREAD

**Issue by L0891-3BDBFF** [un-lock-able/win-acme-dns-validation-aliyun#1]
Script error: Traceback (most recent call last):
 Script error:   File "renewSSL.py", line 64, in <module>
 Script error:   File "renewSSL.py", line 51, in main
 Script error: FileNotFoundError: [Errno 2] No such file or directory: '{install_directory}\\../../python/renewSSLScript/settings.json'
 Script error: [45812] Failed to execute script 'renewSSL' due to unhandled exception!
 Script finished with exit code 1

I used the packed exe version, and I do what README says, but the script can't run

**Comment by un-lock-able** [comment]
I'm sorry to know that, but since now I am not using Aliyun as my DNS provider anymore so I'm not sure what happened to this script. However, I think this issue may be caused by the packing application used to pack the python script into the excutable exe. I wonder if it is possible for you to try excuting the script with python interpreter directly and see if the problem persists?

**Comment by L0891-3BDBFF** [comment]
I try to run the python script from command line and it throw this:

E:\acme\aliyun\py>python renewSSL.py
Traceback (most recent call last):
  File "renewSSL.py", line 5, in <module>
    from aliyunsdkalidns.request.v20150109.AddDomainRecordRequest import AddDomainRecordRequest
ModuleNotFoundError: No module named 'aliyunsdkalidns'

is something missing?(I have installed Aliyun python SDK)

**Comment by L0891-3BDBFF** [comment]
> I'm sorry to know that, but since now I am not using Aliyun as my DNS provider anymore so I'm not sure what happened to this script. However, I think this issue may be caused by the packing application used to pack the python script into the excutable exe. I wonder if it is possible for you to try excuting the script with python interpreter directly and see if the problem persists?

I try to run the python script from command line and it throw this:

E:\acme\aliyun\py>python renewSSL.py
Traceback (most recent call last):
File "renewSSL.py", line 5, in
from aliyunsdkalidns.request.v20150109.AddDomainRecordRequest import AddDomainRecordRequest
ModuleNotFoundError: No module named 'aliyunsdkalidns'

is something missing?(I have installed Aliyun python SDK)

**Comment by un-lock-able** [comment]
> ModuleNotFoundError: No module named 'aliyunsdkalidns'
> 
> is something missing?(I have installed Aliyun python SDK)

From my memory, to use the dns part of the aliyun api, you have to install the `aliyun-python-sdk-alidns` package alongside with the `aliyun-python-sdk-core`.

Try cheking your installed package by 
```shell
pip list
```
to check if you have installed both.

If not, try install them by 
```shell
pip install aliyun-python-sdk-core aliyun-python-sdk-alidns==3.0.7
```
and run the script again to see if it works?

I have also added a `requirement.txt` file in ec68873.   You may also try to install these packages using
```shell
pip install -r requirements.txt
```
when you are in the project directory. Again I'm sorry that since I'm no longer hosting my DNS on aliyun, I did not test whether this will fix the problem.
